version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: mysql
    ports: 
    - target: 3306
      published: 3306
      protocol: tcp
    volumes: 
    - type: bind
      source: ./db/CreateTable.sql
      target: /docker-entrypoint-initdb.d/CreateTable.sql
    environment:
      MYSQL_DATABASE: flask_db
      MYSQL_ROOT_PASSWORD: ${password}
  flask-app:
    image: sjknapp/flask-app
    build: ./flask-app/
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  nginx:
    image: nginx:latest
    ports: 
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
        
